getwd()
dir.create("raw.data")
dir.create("clean.data")
dir.create("scripts")
dir.create("results")
dir.create("tasks")
dir.create("plots")
str("patient_info")
class("patient_info$gender")
class("patient_info$age")
class("patient_info$diagnosis")
class("patient_info$bmi")
class("patient_info$smoker")
class("patient_info$patient_id")
patient_info$smoking_binary <- as.factor("patient_info$smoker")
data$smoker_num <- ifelse(data$smoker_fac == "Yes", 1, 0)
write.csv(data, "clean_data/patient_info_clean.csv")
